name: maven-release
on:
  release:
    types: [published]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: target/VoxelSniper*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}